export const levels = [
    {
        name: 'Level 1',
        class: 'game-board-level1',
        numberOfPairs: 6,
        backgroundImg: './img/backgrounds/green-forest.svg',
        cardImgs: [
            './img/cards/animals/bunny.svg',
            './img/cards/animals/dalmatian.svg',
            './img/cards/animals/dog.svg',
            './img/cards/animals/elephant.svg',
            './img/cards/animals/froggy.svg',
            './img/cards/animals/giraffe.svg',
            './img/cards/animals/goat.svg',
            './img/cards/animals/kitty.svg',
            './img/cards/animals/monkey-face.svg',
            './img/cards/animals/owl.svg',
            './img/cards/animals/panda.svg',
            './img/cards/animals/penguin.svg',
            './img/cards/animals/rhino.svg',
            './img/cards/animals/seal.svg',
            './img/cards/animals/sheep.svg',
            './img/cards/animals/squirrel.svg',
            './img/cards/animals/tiger.svg',
            './img/cards/animals/zebra.svg',
        ]
    },
    {
        name: 'Level 2',
        class: 'game-board-level2',
        numberOfPairs: 10,
        backgroundImg: './img/backgrounds/car-overpass.jpg',
        cardImgs: [
            './img/cards/cars/big-truck.svg',
            './img/cards/cars/blue-911.svg',
            './img/cards/cars/blue-mini-cab.svg',
            './img/cards/cars/blue-old-bmw.svg',
            './img/cards/cars/brown-muscle-car.svg',
            './img/cards/cars/chevy-55.svg',
            './img/cards/cars/cobra.svg',
            './img/cards/cars/ferrari-racer.svg',
            './img/cards/cars/green-lambo.svg',
            './img/cards/cars/grey-mx5.svg',
            './img/cards/cars/monster-truck.svg',
            './img/cards/cars/police-car.svg',
            './img/cards/cars/purple-corvette.svg',
            './img/cards/cars/purple-muscle-car.svg',
            './img/cards/cars/red-amg.svg',
            './img/cards/cars/red-citroen.svg',
            './img/cards/cars/red-classic.svg',
            './img/cards/cars/red-f1.svg',
            './img/cards/cars/red-jdm.svg',
            './img/cards/cars/red-lambo.svg',
            './img/cards/cars/red-old-timer.svg',
            './img/cards/cars/red-sports-car.svg',
            './img/cards/cars/silver-mustang.svg',
            './img/cards/cars/tanker-truck.svg',
            './img/cards/cars/tipper-truck.svg',
            './img/cards/cars/yellow-car.svg',
            './img/cards/cars/yellow-f1.svg',
            './img/cards/cars/yellow-gallardo.svg',
        ]
    },
    {
        name: 'Level 3',
        class: 'game-board-level3',
        numberOfPairs: 15,
        backgroundImg: './img/backgrounds/space-the-initial-frontier.svg',
        cardImgs: [
            './img/cards/space/antenna.svg',
            './img/cards/space/astronaut.svg',
            './img/cards/space/blue-alien.svg',
            './img/cards/space/blue-ufo.svg',
            './img/cards/space/earth.svg',
            './img/cards/space/green-alien.svg',
            './img/cards/space/jupiter.svg',
            './img/cards/space/moon-rocket.svg',
            './img/cards/space/moon-rocket2.svg',
            './img/cards/space/moon.svg',
            './img/cards/space/red-alien.svg',
            './img/cards/space/red-dotted-alien.svg',
            './img/cards/space/saturn.svg',
            './img/cards/space/space-fighter.svg',
            './img/cards/space/space-invader.svg',
            './img/cards/space/sun.svg',
        ]
    },
]